/** 公共模块 */
export const COMMON_AUTH = 'COMMON_AUTH';
export const COMMON_PERMISSION = 'COMMON_PERMISSION';
export const COMMON_LOAD_DOING = 'COMMON_LOAD_DOING';
export const COMMON_LOAD_DONE = 'COMMON_LOAD_DONE';

/** 用户模块 */
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER = 'USER_REGISTER';

/** 异常模块 */
export const EXCEPTION_LIST_SUCCESS = 'EXCEPTION_LIST_SUCCESS';
export const EXCEPTION_LIST_FAILURE = 'EXCEPTION_LIST_FAILURE';
export const EXCEPTION_FILTER_STATE = 'EXCEPTION_FILTER_STATE';

export const EXCEPTION_DETAIL_SUCCESS = 'EXCEPTION_DETAIL_SUCCESS';
export const EXCEPTION_DETAIL_FAILURE = 'EXCEPTION_DETAIL_FAILURE';
export const EXCEPTION_ADD_SUCCESS = 'EXCEPTION_ADD_SUCCESS';
export const EXCEPTION_ADD_FAILURE = 'EXCEPTION_ADD_FAILURE';
export const EXCEPTION_SLOVE_SUCCESS = 'EXCEPTION_SLOVE_SUCCESS';
export const EXCEPTION_SLOVE_FAILURE = 'EXCEPTION_SLOVE_FAILURE';

export const UPDATE_FORM_ITEM = 'UPDATE_FORM_ITEM';
