/** 公共模块 */
export const COMMON_AUTH = 'COMMON_AUTH';
export const COMMON_PERMISSION = 'COMMON_PERMISSION';
export const COMMON_LOAD_DOING = 'COMMON_LOAD_DOING';
export const COMMON_LOAD_DONE = 'COMMON_LOAD_DONE';

/** 用户模块 */
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER = 'USER_REGISTER';

export const USER_PEOPLE_SUCCESS = 'USER_PEOPLE_SUCCESS';
export const USER_PEOPLE_FAILURE = 'USER_PEOPLE_FAILURE';

/** 异常模块 */
export const EXCEPTION_LIST_SUCCESS = 'EXCEPTION_LIST_SUCCESS';
export const EXCEPTION_LIST_FAILURE = 'EXCEPTION_LIST_FAILURE';
export const EXCEPTION_FILTER_STATE = 'EXCEPTION_FILTER_STATE';

export const EXCEPTION_DETAIL_SUCCESS = 'EXCEPTION_DETAIL_SUCCESS';
export const EXCEPTION_DETAIL_FAILURE = 'EXCEPTION_DETAIL_FAILURE';
export const EXCEPTION_ADD_SUCCESS = 'EXCEPTION_ADD_SUCCESS';
export const EXCEPTION_ADD_FAILURE = 'EXCEPTION_ADD_FAILURE';
export const EXCEPTION_SOLVE_SUCCESS = 'EXCEPTION_SOLVE_SUCCESS';
export const EXCEPTION_SOLVE_FAILURE = 'EXCEPTION_SOLVE_FAILURE';

export const EXCEPTION_POLLING_ITEM_SUCCESS = 'EXCEPTION_POLLING_ITEM_SUCCESS';
export const EXCEPTION_POLLING_ITEM_FAILURE = 'EXCEPTION_POLLING_ITEM_FAILURE';

export const EXCEPTION_RIVER_SUCCESS = 'EXCEPTION_RIVER_SUCCESS';
export const EXCEPTION_RIVER_FAILURE = 'EXCEPTION_RIVER_FAILURE';

export const EXCEPTION_REACH_SUCCESS = 'EXCEPTION_REACH_SUCCESS';
export const EXCEPTION_REACH_FAILURE = 'EXCEPTION_REACH_FAILURE';

export const EXCEPTION_CHILD_AREA_SUCCESS = 'EXCEPTION_CHILD_AREA_SUCCESS';
export const EXCEPTION_CHILD_AREA_FAILURE = 'EXCEPTION_CHILD_AREA_FAILURE';

export const EXCEPTION_RIVER_STATE = 'EXCEPTION_RIVER_STATE';
export const EXCEPTION_REACH_STATE = 'EXCEPTION_REACH_STATE';
export const EXCEPTION_CHILD_AREA_STATE = 'EXCEPTION_CHILD_AREA_STATE';
export const EXCEPTION_POLLING_ITEM_STATE = 'EXCEPTION_POLLING_ITEM_STATE';
export const EXCEPTION_ADD_EXCEPTION_STATE = 'EXCEPTION_ADD_EXCEPTION_STATE';
export const EXCEPTION_GET_ROOT_AREA_CODE_STATE = 'EXCEPTION_GET_ROOT_AREA_CODE_STATE';

export const UPDATE_FORM_ITEM = 'UPDATE_FORM_ITEM';

/** 巡检模块 */
export const PATROL_CHILD_AREA_SUCCESS = 'PATROL_CHILD_AREA_SUCCESS';
export const PATROL_CHILD_AREA_FAILURE = 'PATROL_CHILD_AREA_FAILURE';

export const PATROL_INFO_SUCCESS = 'PATROL_INFO_SUCCESS';
export const PATROL_INFO_FAILURE = 'PATROL_INFO_FAILURE';

export const POLLING_PEOPLE_SUCCESS = 'POLLING_PEOPLE_SUCCESS';
export const POLLING_PEOPLE_FAILURE = 'POLLING_PEOPLE_FAILURE';

export const POLLING_RECORD_SUCCESS = 'POLLING_RECORD_SUCCESS';
export const POLLING_RECORD_FAILURE = 'POLLING_RECORD_FAILURE';

export const POLLING_RIVER_LIST_SUCCESS = 'POLLING_RIVER_LIST_SUCCESS';
export const POLLING_RIVER_LIST_FAILURE = 'POLLING_RIVER_LIST_FAILURE';

export const PATROL_CHILD_AREA_STATE = 'PATROL_CHILD_AREA_STATE';

export const PATROL_CHART_SUCCESS = 'PATROL_CHART_SUCCESS';
export const PATROL_CHART_FAILURE = 'PATROL_CHART_FAILURE';

export const PATROL_PHASES_SUCCESS = 'PATROL_PHASES_SUCCESS';
export const PATROL_PHASES_FAILURE = 'PATROL_PHASES_FAILURE';

export const PATROL_RIVER_SYSTEM_SUCCESS = 'PATROL_RIVER_SYSTEM_SUCCESS';
export const PATROL_RIVER_SYSTEM_FAILURE = 'PATROL_RIVER_SYSTEM_FAILURE';

export const PATROL_RIVER_SUCCESS = 'PATROL_RIVER_SUCCESS';
export const PATROL_RIVER_FAILURE = 'PATROL_RIVER_FAILURE';

export const PATROL_TRACK_SUCCESS = 'PATROL_TRACK_SUCCESS';
export const PATROL_TRACK_FAILURE = 'PATROL_TRACK_FAILURE';

export const POLLING_GET_PATROL_FULL_DETAIL_SUCCESS = 'POLLING_GET_PATROL_FULL_DETAIL_SUCCESS';
export const POLLING_GET_PATROL_FULL_DETAIL_FAILURE = 'POLLING_GET_PATROL_FULL_DETAIL_FAILURE';